# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xci
# IP: The module: 'axi_quad_spi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xci
# IP: The module: 'axi_quad_spi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wolf/minisys-rocket-chip/minisys_rocket_chip_vivado_project/minisys_rocket_chip_vivado_project.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_quad_spi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
